<!DOCTYPE html>
<html>
    <title></title>
    <header>
        <!-- <link rel="stylesheet" href="https://dnmtechs.com/project/checkip/css/bootstrap.min.css"> -->
        <link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('DxT_Weather::css/source/weather.css') ?>">
    </header>

    <body>
        <div class="container-weather">
            <?php
                $access_key = "&appid=2094f2f05473cadc889af07c7c186dde";
                $ip_obj = $block->sendJsontoServer();
                $country = $ip_obj->country_name;
                $region = $ip_obj->region_name;
                if(!$region){
                    $region = $ip_obj->location->capital;
                }
                $current_obj = $block->getCurrentData($region, $country, $access_key);
                $city_id = $current_obj->id;
                $forcast_obj = $block->getForcast($city_id, $access_key);
            ?>
            <div class="title">Weather
            </div>
            <div class="weather-now">
                <div class="row">
                    <div class="">Location: <?php echo $region.", ".$country ?></div>
                    <div class="">Update Time: <?php echo date("d/m/Y H:i:s",$current_obj->dt); ?></div>
                </div>
                <div class="row">
                    <div class="">
                        <div style="height:50px; width:50px; margin-left:auto;margin-right:auto;
                             background: url('http://openweathermap.org/img/w/<?php echo $current_obj->weather[0]->icon ?>.png');background-size: cover;"></div>
                        <div><?php echo $current_obj->main->temp." &#8451;" ?> - <?php echo  $current_obj->weather[0]->main ?></div>
                        <div>Cloudiness: <?php echo $current_obj->clouds->all."%" ?></div>
                    </div>
                    <div class="weather-info">
                        <div>Pressure: <?php echo $current_obj->main->pressure."hPa" ?></div>
                        <div>Humidity: <?php echo $current_obj->main->humidity."%" ?></div>
                        <div>Min Temp: <?php echo $current_obj->main->temp_min." &#8451;" ?></div>
                        <div>Max Temp: <?php echo $current_obj->main->temp_max." &#8451;" ?></div>
                    </div>
                </div>
                <div class="row">
                    <div class="weather-info">Wind Speed: <?php echo $current_obj->wind->speed." meter/sec" ?></div>
                    <div class="weather-info">Wind Direction: <?php echo $current_obj->wind->deg."&deg;" ?></div>
                </div>
                <div class="row">
                    <div class="weather-info">Sunrise: <?php echo date("H:i:s",$current_obj->sys->sunrise); ?></div>
                    <div class="weather-info">Sunset: <?php echo date("H:i:s",$current_obj->sys->sunset); ?></div>
                </div>
            </div>
            <div class="row">
                    <?php 
                        $forcast_list = $forcast_obj->list;
                        foreach($forcast_list as $temp)
                            if(date("d/m",$current_obj->dt) == date("d/m",$temp->dt)) {?>
                <div class="">
                    <div class=""><b><?php echo date("d/m H:i",$temp->dt) ?></b></div>
                    <div class="" style="height:50px; width:50px; margin-left:auto;margin-right:auto;
                    background: url('http://openweathermap.org/img/w/<?php echo $temp->weather[0]->icon ?>.png') no-repeat;"></div>
                    <div class="weather-info"><?php echo $temp->main->temp." &#8451;" ?></div>
                    <div class="weather-info"><?php echo $temp->main->humidity."%" ?></div>
                    <div class="weather-info"><?php echo $temp->weather[0]->main ?></div>
                </div>
                <?php } 
                    ?>
            </div>
        </div>
    </body>
</html>